LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := send.c
LOCAL_SHARED_LIBRARIES :=
LOCAL_CFLAGS += -static
LOCAL_CPPFLAGS +=
LOCAL_MODULE := sendtest
LOCAL_MODULE_TAGS := optional
include $(BUILD_EXECUTABLE)

